<BusTracker>:
    orientation: 'vertical'
    
    # ... (Section affichage retard reste la même) ...

    BoxLayout:
        size_hint_y: 0.15
        spacing: 5
        Button:
            text: "CAPTURER"
            on_press: root.save_current_pos()
        Button:
            text: "ÉDITER LIGNE"
            background_color: (1, 0.5, 0, 1) # Orange
            on_press: root.ouvrir_menu_edition()